python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - develop
    - method: setuptools
      path: .

sphinx:
  builder: dirhtml
  configuration: docs/source/conf.py
  fail_on_warning: false

version: 2
