language: python
python: 3.6
branches:
  except: /^v\.\d\.\d\.\d/
before_install: pip install babel
install: pip install --upgrade .
script:
  - python setup.py compile_catalog
  - python -m tests
before_deploy: |
  version="v$(python -c "print(__import__('pkg_resources').get_distribution('lib50').version)")"
  if [ -z "$(git tag --list "$version")" ]; then \
      git config --local user.name "bot50"; \
      git config --local user.email "bot@cs50.harvard.edu"; \
      git tag "$version"; \
  fi
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    skip_cleanup: true
    on:
      branch: main
  - provider: pypi
    user: "$PYPI_USERNAME"
    password: "$PYPI_PASSWORD"
    skip_cleanup: true
    on:
      branch: main
